DBPATH = "/Users/thdg/PycharmProjects/eWalletv1/ewallet.db"
INITIALIZED = 'INITIALIZED'
CONFIRMED = 'CONFIRMED'
VERIFIED = 'VERIFIED'
COMPLETED = 'COMPLETED'
CANCELED = 'CANCELED'
EXPIRED = 'EXPIRED'
FAILED = 'FAILED'